#!/usr/bin/env bash

url=$1

invalid_arguments()
{
	echo "Usage: $0 ssh://[user[:pass]]@host:port" 1>&2
	exit 1
}

[ -z "$url" ] && invalid_arguments

url="${url#*ssh://}"
url="${url%/*}"

credentials="${url%@*}"
address="${url#*@}"

host="${address%:*}"
[ "$host" = "$address" ] && port=22 || port="${address#*:}"

[ -z "$host" ] && invalid_arguments

user="${credentials%:*}"
pass="${credentials#*:}"

# Set TERM=xterm if using alacritty or termite
[ "$TERM" = alacritty -o "$TERM" = "xterm-termite" ] && TERM=xterm

if [ -z "$pass" ]
then
	[-z "$user"] && ssh -o "UserKnownHostsFile=/dev/null" -p "$port" "$host" || ssh -p "$port" "$user@$host"
else
	[ -z "$user" ] && invalid_arguments
	pass.exp "$pass" ssh -o "UserKnownHostsFile=/dev/null" -p "$port" "$user@$host" "$cmd"
fi
